// <auto-generated />
namespace SeleniumLottoDataApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class updated_Cash4Life : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_Cash4Life));
        
        string IMigrationMetadata.Id
        {
            get { return "202108212156448_updated_Cash4Life"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
