// <auto-generated />
namespace SeleniumLottoDataApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_Probability_Number : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Probability_Number));
        
        string IMigrationMetadata.Id
        {
            get { return "202409240521328_add_Probability_Number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
